[package]
name = "osu-song-minifier"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
winreg = "0.10.1"
half = "1.8.2"
tokio = { version = "1.13.0", features = ["full"] }